"""The hand-planted part of the blind evaluation: what the scorer counts, and what the command refuses.

The values used here come from an author seed, which the command line refuses for a blind run: no value a
different hand could ever be given is generated by this test.
"""
import contextlib
import io
import json
import sys
import unittest
from unittest import mock

from tests import _util as u

sys.path.insert(0, str(u.ROOT / "eval"))
import manual  # noqa: E402
import score as harness  # noqa: E402
from corpus import fakes  # noqa: E402
from noascan.scan import scan  # noqa: E402

SEED = u.DEV_SEED
OTHER_AUTHOR_SEED = harness.SEEDS["author_seeds"]["holdout"]     # also refused for a blind run


def by_class():
    out = {}
    for p in manual.plants(SEED):
        out.setdefault(p["class"], p)
    return out


def tree(name, with_other=True, plain=True):
    p = by_class()
    files = dict(u.CLEAN_FILES)
    hidden = {}
    if plain:
        files["deploy/integration.env"] = "LOG_LEVEL=warn\nINTEGRATION_CREDENTIAL=" + p["vendor_api_token"]["value"] + "\n"
        files["src/settings.py"] = "ADMIN_PASSWORD = " + json.dumps(p["assigned_password"]["value"]) + "\n"
        files["deploy/values.yml"] = 'app:\n  databaseUrl: "' + p["connection_uri_password"]["shown"] + '"\n'
        files["keys/deploy.txt"] = p["armored_key_block"]["value"] + "\n"
        for cls in ("vendor_api_token", "assigned_password", "connection_uri_password", "armored_key_block"):
            hidden[p[cls]["id"]] = "plain"
    if with_other:
        files["notes.txt"] = "kept for later, split in two: " + p["vendor_test_key"]["value"][:14] + "\nand " + \
            p["vendor_test_key"]["value"][14:] + "\n"
        hidden[p["vendor_test_key"]["id"]] = "other"
    form = manual.form(SEED, "a-test")
    for entry in form["plants"]:
        if entry["id"] in hidden:
            entry.update(hidden=True, form=hidden[entry["id"]], where="test")
    return u.write_tree(u.tmp(name), files), form


def call(*args):
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = manual.main([str(a) for a in args])
    return code, out.getvalue(), err.getvalue()


class Plants(unittest.TestCase):
    def test_twenty_values_of_every_covered_class_from_the_seed_alone(self):
        a, b = manual.plants(SEED), manual.plants(SEED)
        self.assertEqual(a, b)
        self.assertEqual(len(a), 20)
        self.assertEqual({p["class"] for p in a}, set(fakes.SECRET_CLASSES))
        self.assertEqual(len({p["fingerprint"] for p in a}), 20)
        self.assertNotEqual([p["value"] for p in a], [p["value"] for p in manual.plants(OTHER_AUTHOR_SEED)])

    def test_the_form_holds_fingerprints_and_no_value(self):
        text = json.dumps(manual.form(SEED, "a-test"))
        for p in manual.plants(SEED):
            for line in p["value"].split("\n"):
                if not line.startswith("-----"):
                    self.assertNotIn(line, text)
            self.assertIn(p["fingerprint"], text)


class Score(unittest.TestCase):
    def test_plain_values_are_found_and_nothing_leaks(self):
        root, form = tree("manual-plain")
        res = manual.score(SEED, root, form, u.AS_OF)
        self.assertEqual((res["hidden"], res["plain"], res["plain_found"], res["other"]), (5, 4, 4, 1))
        self.assertEqual((res["verdict"], res["never_event"], res["secret_values_in_reports"]), ("BLOCKED", 0, 0))
        self.assertIn("no claim about any real system", res["statement"])

    def test_a_clean_verdict_with_a_plain_value_is_counted_as_the_never_event(self):
        root, form = tree("manual-never")
        template = scan(u.write_tree(u.tmp("manual-template"), u.CLEAN_FILES), u.AS_OF)
        self.assertEqual(template["verdict"], "CLEAN")
        with mock.patch.object(manual, "scan", side_effect=lambda *a, **k: json.loads(json.dumps(template))):
            res = manual.score(SEED, root, form, u.AS_OF)
        self.assertEqual((res["never_event"], res["plain_found"]), (1, 0))

    def test_a_value_hidden_outside_the_promise_is_reported_apart(self):
        root, form = tree("manual-other", plain=False)
        res = manual.score(SEED, root, form, u.AS_OF)
        self.assertEqual((res["plain"], res["other"], res["never_event"]), (0, 1, 0))
        self.assertEqual(res["clean_with_only_out_of_coverage_secret"], int(res["verdict"] == "CLEAN"))

    def test_a_form_that_is_not_filled_or_is_of_another_seed_is_refused(self):
        root, form = tree("manual-bad")
        with self.assertRaises(ValueError):
            manual.score(OTHER_AUTHOR_SEED, root, form, u.AS_OF)
        form["plants"][0].update(hidden=True, form="")
        with self.assertRaises(ValueError):
            manual.score(SEED, root, form, u.AS_OF)


class CommandLine(unittest.TestCase):
    def test_the_author_seeds_are_refused(self):
        for seed in harness.SEEDS["author_seeds"].values():
            code, out, err = call("values", "--seed", seed, "--runner", "someone-else")
            self.assertEqual((code, out), (64, ""))
            self.assertIn("used by the author", err)

    def test_a_seed_of_an_earlier_blind_run_is_refused_before_any_value_is_drawn(self):
        for entry in harness.SEEDS["seen_seeds"]:
            with mock.patch.object(manual, "plants", side_effect=AssertionError("a refused run must not draw values")):
                code, out, err = call("values", "--seed", entry["seed"], "--runner", "someone-else")
            self.assertEqual((code, out), (64, ""))
            self.assertIn("earlier blind run", err)

    def test_without_the_freeze_tag_nothing_is_printed(self):
        with mock.patch.object(harness, "FREEZE_TAG", "v0.0.0-no-such-tag"), \
                mock.patch.object(manual, "plants", side_effect=AssertionError("a refused run must not draw values")):
            code, out, err = call("values", "--seed", 7, "--runner", "someone-else")
        self.assertEqual((code, out), (64, ""))
        self.assertIn("not a blind run", err)


if __name__ == "__main__":
    unittest.main()
